Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,24 +2,25 @@ name: Main-Actions
 on: push
 jobs:
   job-1:
-    if: always() == false
     runs-on: ubuntu-latest
     outputs:
       validation_result: ${{ steps.step1.outputs.validation_result }}
     steps:
-    - id: step1
-      name: Validate branch name
-      run: |
-        echo "validation_result=success" >> "$GITHUB_OUTPUT"
-    - name: Print the value - Job-1
-      run: echo "This is 1st Job"
+      - id: step1
+        name: Validate branch name
+        run: |
+          if [[ "${GITHUB_HEAD_REF}" != "master" ]]; then
+            echo "validation_result=failed" >> "$GITHUB_OUTPUT"
+            exit 1
+          else
+            echo "validation_result=success" >> "$GITHUB_OUTPUT"
+          fi
+      - name: Print the value - Job-1
+        run: echo "This is 1st Job"
   job-2:
     needs: job-1
     runs-on: ubuntu-latest
-    if: always() || needs.validate-branch-name.result == 'skipped' 
+    if: needs.job-1.result == 'success' || needs.job-1.result == 'skipped'
     steps:
-    - name: Print the value - Job-2
-      run: |
-        echo "Outputs: ${{ needs.job-1.outputs.validation_result }}"
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
